# Generated by Django 4.2.11 on 2024-08-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininghallreview',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
