# Generated by Django 4.2.11 on 2024-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
