# Generated by Django 4.2.11 on 2024-08-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_tag_post_likes_post_media_post_view_count_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.reportoption'),
        ),
    ]
